import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Icon } from "@iconify/react";

const rows = [["3,000만", "224.2만"], ["4,000만", "290.8만"], ["5,000만", "355.4만"], ["6,000만", "418.9만"], ["7,000만", "482.4만"], ["8,000만", "540.4만"], ["9,000만", "599.3만"], ["1억", "658.7만"]];

export const metadata: Metadata = { title: "Codex 디자인 시안 | 2026 연봉 실수령액", robots: { index: false, follow: false } };

export default function CodexSalaryGuide() {
  return <article className="salary-guide overflow-hidden pb-8">
    <header className="mb-20 grid gap-10 border-b border-zinc-200/70 pb-14 lg:grid-cols-[1.05fr_.95fr] lg:items-end"><div className="break-keep-all"><p className="mb-5 inline-flex rounded-full bg-[#c55232]/10 px-3 py-1.5 text-[11px] font-bold tracking-[.14em] text-[#a74126]">CODEX DESIGN EDITION</p><h1 className="max-w-3xl text-[2.6rem] font-extrabold leading-[1.16] tracking-[-.055em] text-zinc-950 sm:text-5xl lg:text-[4.4rem]">연봉은 숫자고,<br /><span className="font-serif italic font-medium text-[#c55232]">실수령액</span>은 생활입니다.</h1><p className="mt-7 max-w-xl text-base leading-8 text-zinc-600 sm:text-lg">3,000만 원부터 1억 원까지. 월급 명세서에서 실제로 확인하게 될 공제액과 입금액을 편집형 레이아웃으로 정리했습니다.</p><div className="mt-10 flex gap-5 text-sm font-medium text-zinc-500"><span className="flex items-center gap-2"><Icon icon="solar:calendar-mark-bold-duotone" className="text-[#c55232]" />2026.09.22</span><span className="flex items-center gap-2"><Icon icon="solar:clock-circle-bold-duotone" className="text-[#c55232]" />4분 읽기</span></div></div><div className="relative aspect-[5/4] overflow-hidden rounded-[2rem] bg-[#ede8df] p-2 shadow-[0_25px_60px_-32px_rgba(67,45,34,.38)]"><Image src="/images/salary-guide-thumbnail.jpg" alt="2026 연봉 실수령액 안내" fill priority className="rounded-[1.55rem] object-cover" /><div className="absolute bottom-5 left-5 rounded-full bg-[#fdfbf7]/90 px-4 py-2 text-xs font-bold text-zinc-800">기준일 2026.09</div></div></header>
    <section className="mb-24 grid gap-4 border-y border-zinc-200/80 py-7 sm:grid-cols-3">{[["4.75%", "국민연금 근로자 부담"], ["4.0674%", "건강·장기요양 합산"], ["20만 원", "월 식대 비과세 한도"]].map(([number, label]) => <div key={label} className="border-zinc-200/80 px-1 sm:border-r sm:px-7 sm:last:border-0"><p className="text-3xl font-extrabold tracking-[-.05em] text-zinc-950">{number}</p><p className="mt-2 text-sm font-bold text-zinc-800">{label}</p></div>)}</section>
    <section className="mb-24 grid gap-8 lg:grid-cols-[.82fr_1.18fr] lg:items-center"><div className="break-keep-all"><p className="text-xs font-bold tracking-[.16em] text-[#c55232]">QUICK ANSWER</p><h2 className="mt-4 text-3xl font-extrabold leading-snug tracking-[-.045em] text-zinc-950 sm:text-4xl">내 연봉의 진짜 월급은<br />얼마일까요?</h2><p className="mt-5 max-w-md leading-7 text-zinc-600">부양가족 본인 1명, 퇴직금 별도, 월 식대 20만 원 비과세를 가정한 참고값입니다.</p><Link href="/salary-calculator" className="mt-8 inline-flex min-h-12 items-center gap-3 rounded-full bg-[#c55232] py-2 pl-6 pr-2 text-sm font-bold text-white transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] hover:scale-[1.02]">내 조건으로 계산하기 <span className="grid size-8 place-items-center rounded-full bg-white/15"><Icon icon="solar:arrow-right-linear" /></span></Link></div><div className="rounded-[2rem] bg-[#292520] p-2"><div className="rounded-[1.6rem] border border-white/10 bg-[#332e29] p-8 text-[#fdfbf7]"><p className="text-xs font-bold tracking-[.15em] text-[#e8b3a2]">EXAMPLE · 연봉 5,000만 원</p><p className="mt-9 text-sm text-[#d8d0c7]">예상 월 실수령액</p><p className="mt-1 text-5xl font-extrabold tracking-[-.07em]">355.4<span className="ml-1 text-xl text-[#d8d0c7]">만 원</span></p><div className="mt-9 grid grid-cols-2 border-t border-white/10 pt-5 text-sm"><div><p className="text-[#b9aea4]">보험료</p><p className="mt-1 font-bold">약 38.5만 원</p></div><div className="border-l border-white/10 pl-5"><p className="text-[#b9aea4]">소득·지방세</p><p className="mt-1 font-bold">약 22.7만 원</p></div></div></div></div></section>
    <section className="mb-24"><p className="text-xs font-bold tracking-[.16em] text-[#c55232]">SALARY TABLE</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.045em] text-zinc-950 sm:text-4xl">연봉 구간별 예상 실수령액</h2><div className="mt-8 overflow-hidden rounded-[1.75rem] border border-zinc-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-[#f3efe8] text-xs font-bold text-zinc-600"><tr><th className="px-6 py-5">세전 연봉</th><th className="px-6 py-5 text-right text-[#a74126]">예상 월 실수령액</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row[0]} className={index === 2 ? "bg-[#fdf5f1]" : "border-t border-zinc-100"}><td className="px-6 py-5 font-extrabold text-zinc-900">{row[0]} 원</td><td className="px-6 py-5 text-right text-lg font-extrabold text-[#a74126]">{row[1]}</td></tr>)}</tbody></table></div></section>
    <section className="mb-24 rounded-[2rem] bg-[#e8e3da] p-8 sm:p-12"><p className="text-xs font-bold tracking-[.16em] text-[#a74126]">TAX-FREE MEAL ALLOWANCE</p><h2 className="mt-3 text-3xl font-extrabold leading-snug tracking-[-.045em] text-zinc-950 sm:text-4xl">식대 20만 원을<br />그냥 넘기지 마세요.</h2><p className="mt-6 max-w-2xl leading-8 text-zinc-700">식사를 제공받지 않는 근로자에게 지급하는 식대는 요건 충족 시 월 20만 원까지 비과세가 적용될 수 있습니다. 과세 대상 급여가 줄어 세금과 보험료 부담에도 영향을 줍니다.</p></section>
    <section className="rounded-[2rem] bg-[#292520] px-7 py-12 text-center text-[#fdfbf7] sm:px-12 sm:py-16"><p className="text-xs font-bold tracking-[.18em] text-[#e8b3a2]">YOUR NUMBER, NOT AN AVERAGE</p><h2 className="mx-auto mt-4 max-w-2xl break-keep-all text-3xl font-extrabold leading-snug tracking-[-.045em] sm:text-4xl">부양가족과 비과세액까지<br />내 조건으로 확인하세요.</h2><Link href="/salary-calculator" className="mt-8 inline-flex min-h-12 items-center gap-3 rounded-full bg-[#fdfbf7] py-2 pl-6 pr-2 text-sm font-bold text-zinc-900 transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] hover:scale-[1.02]">연봉 실수령액 계산기 <span className="grid size-8 place-items-center rounded-full bg-zinc-900 text-white"><Icon icon="solar:arrow-right-linear" /></span></Link></section>
  </article>;
}
